FROM node:22-slim AS build
RUN corepack enable
WORKDIR /app
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile
COPY . .
# NEXT_PUBLIC values are compiled into the browser bundle, so deployment policy
# must be supplied as build arguments rather than only as container runtime env.
ARG NEXT_PUBLIC_SITE_URL
ENV NEXT_PUBLIC_SITE_URL=${NEXT_PUBLIC_SITE_URL}
ARG NEXT_PUBLIC_LCE_CLIENT_PACKAGE_RUNNER
ENV NEXT_PUBLIC_LCE_CLIENT_PACKAGE_RUNNER=${NEXT_PUBLIC_LCE_CLIENT_PACKAGE_RUNNER}
ARG NEXT_PUBLIC_LCE_CLIENT_PACKAGE_RUNNER_ARGS
ENV NEXT_PUBLIC_LCE_CLIENT_PACKAGE_RUNNER_ARGS=${NEXT_PUBLIC_LCE_CLIENT_PACKAGE_RUNNER_ARGS}
ARG NEXT_PUBLIC_LCE_CLIENT_PACKAGE_NAME
ENV NEXT_PUBLIC_LCE_CLIENT_PACKAGE_NAME=${NEXT_PUBLIC_LCE_CLIENT_PACKAGE_NAME}
ARG NEXT_PUBLIC_LCE_CLIENT_PACKAGE_TAG
ENV NEXT_PUBLIC_LCE_CLIENT_PACKAGE_TAG=${NEXT_PUBLIC_LCE_CLIENT_PACKAGE_TAG}
ARG NEXT_PUBLIC_LCE_CLIENT_GLOBAL_EXECUTABLE
ENV NEXT_PUBLIC_LCE_CLIENT_GLOBAL_EXECUTABLE=${NEXT_PUBLIC_LCE_CLIENT_GLOBAL_EXECUTABLE}
ARG NEXT_PUBLIC_APPLICATION_TIMEZONE
ENV NEXT_PUBLIC_APPLICATION_TIMEZONE=${NEXT_PUBLIC_APPLICATION_TIMEZONE}
ARG NEXT_PUBLIC_INDEX_POLL_ACTIVE_MS
ENV NEXT_PUBLIC_INDEX_POLL_ACTIVE_MS=${NEXT_PUBLIC_INDEX_POLL_ACTIVE_MS}
ARG NEXT_PUBLIC_INDEX_POLL_IDLE_MS
ENV NEXT_PUBLIC_INDEX_POLL_IDLE_MS=${NEXT_PUBLIC_INDEX_POLL_IDLE_MS}
ARG NEXT_PUBLIC_LOGS_AUTO_REFRESH_MS
ENV NEXT_PUBLIC_LOGS_AUTO_REFRESH_MS=${NEXT_PUBLIC_LOGS_AUTO_REFRESH_MS}
ARG NEXT_PUBLIC_LOGS_PAGE_SIZE
ENV NEXT_PUBLIC_LOGS_PAGE_SIZE=${NEXT_PUBLIC_LOGS_PAGE_SIZE}
ARG NEXT_PUBLIC_LEADERBOARD_REFRESH_MS
ENV NEXT_PUBLIC_LEADERBOARD_REFRESH_MS=${NEXT_PUBLIC_LEADERBOARD_REFRESH_MS}
ARG NEXT_PUBLIC_LEADERBOARD_DATE_OPTION_COUNT
ENV NEXT_PUBLIC_LEADERBOARD_DATE_OPTION_COUNT=${NEXT_PUBLIC_LEADERBOARD_DATE_OPTION_COUNT}
ARG NEXT_PUBLIC_PAYMENT_STATUS_POLL_MS
ENV NEXT_PUBLIC_PAYMENT_STATUS_POLL_MS=${NEXT_PUBLIC_PAYMENT_STATUS_POLL_MS}
ARG NEXT_PUBLIC_HEALTH_HISTORY_LIMIT
ENV NEXT_PUBLIC_HEALTH_HISTORY_LIMIT=${NEXT_PUBLIC_HEALTH_HISTORY_LIMIT}
ARG NEXT_PUBLIC_HEALTH_LATEST_LIMIT
ENV NEXT_PUBLIC_HEALTH_LATEST_LIMIT=${NEXT_PUBLIC_HEALTH_LATEST_LIMIT}
ARG NEXT_PUBLIC_HEALTH_RESULT_POLL_MS
ENV NEXT_PUBLIC_HEALTH_RESULT_POLL_MS=${NEXT_PUBLIC_HEALTH_RESULT_POLL_MS}
ARG NEXT_PUBLIC_HEALTH_RESULT_POLL_ATTEMPTS
ENV NEXT_PUBLIC_HEALTH_RESULT_POLL_ATTEMPTS=${NEXT_PUBLIC_HEALTH_RESULT_POLL_ATTEMPTS}
ARG NEXT_PUBLIC_HEALTH_COUNTDOWN_TICK_MS
ENV NEXT_PUBLIC_HEALTH_COUNTDOWN_TICK_MS=${NEXT_PUBLIC_HEALTH_COUNTDOWN_TICK_MS}
ARG NEXT_PUBLIC_HEALTH_SLOW_THRESHOLD_MS
ENV NEXT_PUBLIC_HEALTH_SLOW_THRESHOLD_MS=${NEXT_PUBLIC_HEALTH_SLOW_THRESHOLD_MS}
ARG NEXT_PUBLIC_HOVER_INTENT_MS
ENV NEXT_PUBLIC_HOVER_INTENT_MS=${NEXT_PUBLIC_HOVER_INTENT_MS}
ARG NEXT_PUBLIC_NOTICE_DURATION_MS
ENV NEXT_PUBLIC_NOTICE_DURATION_MS=${NEXT_PUBLIC_NOTICE_DURATION_MS}
ARG NEXT_PUBLIC_INVITATION_REDIRECT_MS
ENV NEXT_PUBLIC_INVITATION_REDIRECT_MS=${NEXT_PUBLIC_INVITATION_REDIRECT_MS}
ARG NEXT_PUBLIC_MINIMUM_LOADING_FEEDBACK_MS
ENV NEXT_PUBLIC_MINIMUM_LOADING_FEEDBACK_MS=${NEXT_PUBLIC_MINIMUM_LOADING_FEEDBACK_MS}
RUN BETTER_AUTH_SECRET=build-only-7zF4xQ9mK2vN8pR6sT1wY5cH \
    POSTGRES_HOST=localhost \
    NEXT_TELEMETRY_DISABLED=1 \
    pnpm build

FROM node:22-slim
WORKDIR /app
COPY --from=build /app/.next/standalone ./
COPY --from=build /app/.next/static ./.next/static
COPY --from=build /app/public ./public
ENV PORT=3001
EXPOSE 3001
CMD ["node", "server.js"]
